CREATE DATABASE EVENTOS_BBDD;
USE EVENTOS_BBDD;

CREATE TABLE TIPOS
(
    ID_TIPO     INT         NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE      VARCHAR(45) NOT NULL,
    DESCRIPCION VARCHAR(200)
);

CREATE TABLE USUARIOS
(
    USERNAME       VARCHAR(45)  NOT NULL PRIMARY KEY,
    PASSWORD       VARCHAR(255) NOT NULL,
    EMAIL          VARCHAR(100) NOT NULL UNIQUE,
    NOMBRE         VARCHAR(30),
    APELLIDOS      VARCHAR(45),
    DIRECCION      VARCHAR(100),
    ENABLED        INT          NOT NULL DEFAULT 1,
    FECHA_REGISTRO DATE
);

CREATE TABLE PERFILES
(
    ID_PERFIL INT         NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE    VARCHAR(45) NOT NULL
);

CREATE TABLE USUARIO_PERFILES
(
    USERNAME  VARCHAR(45),
    ID_PERFIL INT NOT NULL,
    PRIMARY KEY (USERNAME, ID_PERFIL),
    FOREIGN KEY (USERNAME) REFERENCES USUARIOS (USERNAME),
    FOREIGN KEY (ID_PERFIL) REFERENCES PERFILES (ID_PERFIL)
);

CREATE TABLE EVENTOS
(
    ID_EVENTO         INT         NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE            VARCHAR(50) NOT NULL,
    DESCRIPCION       VARCHAR(200),
    FECHA_INICIO      DATE,
    FECHA_FIN         DATE,
    DURACION          INT,
    DIRECCION         VARCHAR(100),
    UNIDAD_DURACION   VARCHAR(15),
    ESTADO            ENUM ('ACEPTADO','TERMINADO','CANCELADO'),
    DESTACADO         ENUM ('S','N'),
    AFORO_MAXIMO      INT,
    MINIMO_ASISTENCIA INT,
    PRECIO            DEC(9, 2),
    ID_TIPO           INT         NOT NULL,
    FOREIGN KEY (ID_TIPO) REFERENCES TIPOS (ID_TIPO)

);

CREATE TABLE RESERVAS
(
    ID_RESERVA    INT         NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_EVENTO     INT         NOT NULL,
    USERNAME      VARCHAR(45) NOT NULL,
    PRECIO_VENTA  DEC(9, 2),
    OBSERVACIONES VARCHAR(200),
    CANTIDAD      INT,
    FOREIGN KEY (USERNAME) REFERENCES USUARIOS (USERNAME),
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS (ID_EVENTO),
    check (cantidad between 1 and 10),
    UNIQUE (ID_EVENTO, USERNAME)

);

INSERT INTO tipos (nombre, descripcion)
VALUES ('Conferencia', 'Evento de tipo conferencia');
INSERT INTO tipos (nombre, descripcion)
VALUES ('Taller', 'Evento de tipo taller');
INSERT INTO tipos (nombre, descripcion)
VALUES ('Seminario', 'Evento de tipo seminario');
INSERT INTO tipos (nombre, descripcion)
VALUES ('Boda', 'Evento de tipo boda');




